const content = document.getElementById("content");
const catNav = document.getElementById("catNav");

function levelLabel(l) {
  return { mvp: t("level.mvp"), release: t("level.release") }[l];
}

/* Convert How-To text into a visual ordered list.
   Authors write steps as plain text like "1) Do this. 2) Then do that. 3) ...".
   To make it easier to read we split the text into <ol> and <li> elements; the
   numeric markers (1), 2), ...) are regenerated by a CSS counter. If the text
   has no numbered structure (single paragraph, no numbers) we return it as is.
   Placeholder values (just a dash) are also returned unchanged.

   keyPrefix: a feature + level identifier (e.g. "1.1.mvp"). When provided, each
   <li> gets data-step-key="{prefix}.s{i}" and receives the "checked" class if
   state[stepKey] is true. This turns the steps into independently checkable /
   savable checklist items. Without keyPrefix the output is display-only. */
/* Return the number of numbered steps in a How-To string. Uses the same
   pattern as formatHowtoSteps so we can know the count before rendering DOM. */
function countHowtoSteps(html) {
  if (!html || typeof html !== "string") return 0;
  if (!/\b1\)\s/.test(html)) return 0;
  const parts = html.split(/\s*(\d+)\)\s+/);
  if (parts.length < 3) return 0;
  let count = 0;
  for (let i = 1; i + 1 < parts.length; i += 2) {
    if (parts[i + 1].trim()) count++;
  }
  return count;
}

/* Return the number of checked steps for a given level. prefix = "1.1.mvp",
   total = total number of steps for that level. */
function countCheckedStepsByPrefix(prefix, total) {
  if (!total || !state) return 0;
  let n = 0;
  for (let i = 0; i < total; i++) {
    if (state[`${prefix}.s${i}`]) n++;
  }
  return n;
}

function formatHowtoSteps(html, keyPrefix) {
  if (!html || typeof html !== "string") return html;
  /* Pattern for numbered steps: a digit followed by ')' preceded by whitespace
     (or the start of the string). Capture any intro text that appears before
     the "1)" marker, then extract the 2), 3), ... segments in order. */
  if (!/\b1\)\s/.test(html)) return html;
  const parts = html.split(/\s*(\d+)\)\s+/);
  /* parts: [intro_or_empty, "1", step1, "2", step2, ...] */
  if (parts.length < 3) return html;
  const intro = parts[0].trim();
  const items = [];
  for (let i = 1; i + 1 < parts.length; i += 2) {
    items.push(parts[i + 1].trim());
  }
  if (items.length === 0) return html;
  /* The final segment of keyPrefix is the level (mvp/release). Used to tag
     the <ol> with a color-accent class. */
  const level = keyPrefix ? keyPrefix.split(".").pop() : "";
  const ol = `<ol class="howto-steps${level ? " howto-steps-" + level : ""}">${
    items.map((s, i) => {
      const stepKey = keyPrefix ? `${keyPrefix}.s${i}` : "";
      const isChecked = stepKey && state && state[stepKey];
      const classes = ["howto-step"];
      if (isChecked) classes.push("checked");
      const dataAttr = stepKey
        ? ` data-step-key="${stepKey}" role="checkbox" aria-checked="${isChecked ? "true" : "false"}" tabindex="0"`
        : "";
      return `<li class="${classes.join(" ")}"${dataAttr}>${s}</li>`;
    }).join("")
  }</ol>`;
  return intro ? `<p class="howto-step-intro">${intro}</p>${ol}` : ol;
}

/* Card flip + height animation, managed from a single function.
   Why: feature-inner is now position:relative with the front face in normal
   flow and the back face absolute. In checklist mode the card therefore
   occupies only the height of the front face (previously a grid stack used
   max(front, back), which left blank space because the back face is much
   taller). During a flip we set an explicit pixel height on inner; CSS has
   a transition defined for height, so it animates over the same duration as
   the rotation. Once the flip-back completes the explicit height is removed
   so the front face drives natural height again (content changes then reflow
   automatically).

   willFlip:
     - true:  add the "flipped" class and animate height to the back face
     - false: remove "flipped" and animate height back to the front face,
              then clear the inline height
*/
function flipFeatureCard(feature, willFlip, opts = {}) {
  if (!feature) return;
  const inner = feature.querySelector(".feature-inner");
  const front = feature.querySelector(".feature-front");
  const back  = feature.querySelector(".feature-back");
  if (!inner || !front || !back) {
    feature.classList.toggle("flipped", willFlip);
    return;
  }

  const already = feature.classList.contains("flipped") === willFlip;

  /* Sync aria-hidden on faces and aria-pressed on the flip button (always
     runs, regardless of which branch we take below). */
  const syncAria = () => {
    front.setAttribute("aria-hidden", willFlip ? "true" : "false");
    back.setAttribute("aria-hidden",  willFlip ? "false" : "true");
    const btn = feature.querySelector(".feature-flip-btn");
    if (btn) btn.setAttribute("aria-pressed", willFlip ? "true" : "false");
  };

  /* Clear any leftover transitionend handler from a prior flip (handles
     fast double-clicks and instant sync immediately after a render). */
  if (feature._flipTransitionEnd) {
    inner.removeEventListener("transitionend", feature._flipTransitionEnd);
    feature._flipTransitionEnd = null;
  }

  /* INSTANT mode: used to silently apply the "review" preference right after
     a render. Only toggles the .flipped class; no explicit height is set. CSS
     handles the height naturally because in the flipped state the back face
     becomes position:relative. This means the card displays correctly even
     when it starts inside a collapsed category (display:none ancestor): no
     JS offsetHeight measurement is taken, so we avoid the height:0 bug that
     would occur if the measurement returned 0. */
  if (opts.instant) {
    /* Clear any explicit height left over from a previous animation. */
    inner.style.height = "";
    feature.classList.toggle("flipped", willFlip);
    syncAria();
    return;
  }

  /* Animated path but the card is already in the requested state: just sync
     aria and return without retriggering the animation. */
  if (already) {
    syncAria();
    return;
  }

  /* If the card is not visible (e.g. inside a collapsed category) offsetHeight
     returns 0 and animating would produce a jump. Just toggle the class and
     return; CSS will give the card the correct height once it becomes visible. */
  const startH = inner.offsetHeight;
  if (startH === 0) {
    inner.style.height = "";
    feature.classList.toggle("flipped", willFlip);
    syncAria();
    return;
  }

  const target  = willFlip ? back : front;
  const targetH = target.offsetHeight;

  /* Pin the current height as an explicit pixel value (auto becomes px). */
  inner.style.height = startH + "px";
  /* Force a reflow so the next style change triggers the transition. */
  void inner.offsetHeight;

  /* Toggle the class and update aria. */
  feature.classList.toggle("flipped", willFlip);
  syncAria();

  /* Inside rAF, set the target height: this kicks off the height transition. */
  requestAnimationFrame(() => {
    inner.style.height = targetH + "px";
  });

  /* When the transition ends, clear the inline height so CSS drives natural
     flow again in both directions (front-relative when flipping back, back-
     relative when flipped). This way later content changes (filter, language,
     etc.) reflow automatically. */
  const onEnd = (e) => {
    if (e.target !== inner) return;
    if (e.propertyName !== "height") return;
    inner.removeEventListener("transitionend", onEnd);
    feature._flipTransitionEnd = null;
    inner.style.height = "";
  };
  feature._flipTransitionEnd = onEnd;
  inner.addEventListener("transitionend", onEnd);
}

/* Expose globally (used by 14-app.js / setAllCardsFlipped). */
window.flipFeatureCard = flipFeatureCard;

/* Called after each render. If the user picked "review" in the welcome flow
   (or switched to it later), silently flip every card to the back face. No
   animation runs because right after a render the DOM is freshly built and
   an animation would feel artificial. When currentMode === "build" this is
   a no-op and cards stay on the default front face. */
function applyInitialCardMode() {
  if (typeof currentMode === "undefined") return;
  if (currentMode !== "review") return;
  document.querySelectorAll(".feature").forEach(f => {
    flipFeatureCard(f, true, { instant: true });
  });
}
window.applyInitialCardMode = applyInitialCardMode;

function renderCategoryNav() {
  catNav.innerHTML = DATA.map(c =>
    `<a href="#cat-${c.id}" data-cat-nav="${c.id}">${c.id}. ${tx(c.title)}</a>`
  ).join("");
}

/* Find the feature inside a category where the user "left off". Builds the
   candidate list according to viewMode (and ignores viewFilter), then returns
   the first unchecked feature. If everything is complete, returns the last
   eligible feature in the category. */
function findCategoryTargetFeature(catId) {
  const cat = DATA.find(c => c.id === catId);
  if (!cat) return null;

  const mvpVal = (f) => resolveLevelText(f, "mvp");
  const releaseVal = (f) => resolveLevelText(f, "release");
  const exists = (v) => v && v !== "—";
  const isMvpExists = (f) => exists(mvpVal(f));
  const isReleaseExists = (f) => exists(releaseVal(f));

  /* Candidate: passes the framework + backend filter and has a level matching
     the current viewMode. */
  const candidates = cat.features.filter(f => {
    if (f.variants && !currentFramework) return false;
    if (isHiddenByBackend(f)) return false;
    if (viewMode === "mvp") return isMvpExists(f);
    if (viewMode === "release") return isReleaseExists(f);
    return isMvpExists(f) || isReleaseExists(f); // both
  });
  if (candidates.length === 0) {
    return cat.features.find(f => !(f.variants && !currentFramework) && !isHiddenByBackend(f)) || null;
  }

  const isIncomplete = (f) => {
    const mvpKey = `${cat.id}.${f.id}.mvp`;
    const releaseKey = `${cat.id}.${f.id}.release`;
    if (viewMode === "mvp") return isMvpExists(f) && !state[mvpKey];
    if (viewMode === "release") return isReleaseExists(f) && !state[releaseKey];
    return (isMvpExists(f) && !state[mvpKey]) || (isReleaseExists(f) && !state[releaseKey]);
  };

  const firstIncomplete = candidates.find(isIncomplete);
  if (firstIncomplete) return firstIncomplete;
  return candidates[candidates.length - 1];
}

/* Smart navigation into a category:
   - Expand the category if it is collapsed
   - Find the target feature and smooth-scroll to it, accounting for the
     sticky toolbar height */
function navigateToCategorySmart(catId) {
  const targetFeat = findCategoryTargetFeature(catId);

  /* Expand the category if it is collapsed. */
  const catSelector = `cat-${catId}`;
  const catEl = document.getElementById(catSelector);
  if (catEl && catEl.classList.contains("collapsed")) {
    catEl.classList.remove("collapsed");
    collapsedCats.delete(catSelector);
    saveCollapsed();
    /* The user triggered an auto-open via the category nav link; treat this
       as a deliberate collapse-state interaction. */
    if (typeof markCollapseTouched === "function") markCollapseTouched();
    /* One more category is now open; re-check whether the Open All / Close
       All toolbar buttons should still appear active. */
    if (typeof updateToolbarButtonStates === "function") updateToolbarButtonStates();
  }

  /* Wait one frame for the layout to expand, then scroll. */
  requestAnimationFrame(() => {
    let target;
    if (targetFeat) {
      const id = `feat-${catId}-${targetFeat.id.replace(/\./g, "-")}`;
      target = document.getElementById(id);
    }
    if (!target) target = catEl; // fallback: the category header

    if (!target) return;

    /* Account for the sticky toolbar height so the target's top edge ends up
       just below the sticky bar instead of behind it. */
    const stickyBar = document.querySelector(".sticky-bar");
    const stickyH = stickyBar ? stickyBar.getBoundingClientRect().height : 0;
    const top = target.getBoundingClientRect().top + window.scrollY - stickyH - 16;
    window.scrollTo({ top: Math.max(0, top), behavior: "smooth" });
  });
}

/* Event delegation for category nav links: cancel the default anchor jump
   and use the smart navigation instead. */
catNav.addEventListener("click", (e) => {
  const a = e.target.closest("a[data-cat-nav]");
  if (!a) return;
  e.preventDefault();
  navigateToCategorySmart(a.dataset.catNav);
});

function renderContent() {
  content.innerHTML = DATA.map(cat => {
    const catTitle = tx(cat.title);
    const catSub = tx(cat.sub);
    const features = cat.features.map(f => {
      /* Hide framework-specific features until a framework has been picked. */
      if (f.variants && !currentFramework) return "";
      /* When the user has picked "noBackend" (or has not picked a backend yet),
         backend-dependent features are hidden completely so the checklist stays
         clean in the "no internet / no server" scenario. */
      if (isHiddenByBackend(f)) return "";
      const mvpVal = resolveLevelText(f, "mvp");
      const releaseVal = resolveLevelText(f, "release");
      const fTitle = tx(f.title);
      const fDesc = tx(f.desc);

      /* How-To (back-face) content: educational text explaining how to achieve
         the goal stated on the front face. Computed up front because the front
         face's partial-progress bar depends on how many steps the back face
         contains. The resolver is the same one used for the front face, so the
         language x style x framework x backend axes apply the same way. If a
         feature has no How-To defined, a low-emphasis "no guide" message is
         shown instead. */
      const howtoMvpRaw = (typeof resolveHowto === "function") ? resolveHowto(f, "mvp") : null;
      const howtoRelRaw = (typeof resolveHowto === "function") ? resolveHowto(f, "release") : null;
      const howtoMvpText = howtoMvpRaw ? tx(howtoMvpRaw) : "";
      const howtoRelText = howtoRelRaw ? tx(howtoRelRaw) : "";
      const isPlaceholder = (s) => !s || (typeof s === "string" && s.trim() === "—");
      const showHowtoMvp = !isPlaceholder(howtoMvpText);
      const showHowtoRel = !isPlaceholder(howtoRelText);
      const hasAnyHowto  = showHowtoMvp || showHowtoRel;

      const levels = ["mvp", "release"].map(L => {
        const value = L === "mvp" ? mvpVal : releaseVal;
        if (!value || value === "—") return "";
        const key = `${cat.id}.${f.id}.${L}`;
        const checked = state[key] ? "checked" : "";
        /* Step progress: how many steps does this level have, and how many
           are checked? When there are no steps, or all/none of them are
           checked, the partial fill and badge are hidden (a fully checked
           level already shows a solid background; zero is the default). */
        const stepText = L === "mvp" ? howtoMvpText : howtoRelText;
        const stepTotal = (typeof countHowtoSteps === "function") ? countHowtoSteps(stepText) : 0;
        const stepDone  = (stepTotal > 0) ? countCheckedStepsByPrefix(key, stepTotal) : 0;
        const showPartial = stepTotal > 0 && stepDone > 0 && stepDone < stepTotal;
        const pct = stepTotal > 0 ? Math.round((stepDone / stepTotal) * 100) : 0;
        const styleAttr = showPartial ? ` style="--step-progress: ${pct}%;"` : "";
        const badgeHtml = showPartial
          ? `<span class="level-progress-badge" aria-label="${stepDone} / ${stepTotal}">${pct}%</span>`
          : "";
        return `
          <div class="level ${L} ${checked}" data-key="${key}"${styleAttr}>
            <span class="check"></span>
            <span class="level-tag">${levelLabel(L)}</span>
            <span class="level-text">${value}</span>
            ${badgeHtml}
          </div>`;
      }).join("");

      const noteId = `${cat.id}.${f.id}`;
      const noteValue = notes[noteId] || "";
      const hasNote = noteValue.trim().length > 0;
      const noteLabel = hasNote ? t("note.mine") : t("note.add");

      const featAnchor = `feat-${cat.id}-${f.id.replace(/\./g, "-")}`;

      /* Render the How-To as two rows inside a single grid container: first
         column is the label (MVP / Release), second column is the steps.
         Because grid-template-columns is "auto 1fr", every label is aligned
         to the widest one, so even though "Release" is wider than "MVP" the
         step text in both rows starts at the same x position. */
      const mvpStepKeyPrefix = `${cat.id}.${f.id}.mvp`;
      const releaseStepKeyPrefix = `${cat.id}.${f.id}.release`;
      const howtoGridRows = [];
      if (showHowtoMvp) {
        howtoGridRows.push(
          `<span class="howto-tag mvp">${levelLabel("mvp")}</span>` +
          `<div class="howto-text">${formatHowtoSteps(howtoMvpText, mvpStepKeyPrefix)}</div>`
        );
      }
      if (showHowtoRel) {
        howtoGridRows.push(
          `<span class="howto-tag release">${levelLabel("release")}</span>` +
          `<div class="howto-text">${formatHowtoSteps(howtoRelText, releaseStepKeyPrefix)}</div>`
        );
      }
      const howtoBody = hasAnyHowto
        ? `<div class="howto-grid">${howtoGridRows.join("")}</div>`
        : `<p class="howto-empty" data-i18n="howto.empty">${t("howto.empty")}</p>`;

      return `
        <article class="feature${hasNote ? " has-note" : ""}" id="${featAnchor}" data-search="${(fTitle + " " + fDesc + " " + (mvpVal||"") + " " + (releaseVal||"")).toLowerCase().replace(/<[^>]+>/g, "")}" data-note-id="${noteId}">
          <button type="button" class="feature-flip-btn" data-flip-toggle title="${t("howto.flipTitle")}" aria-label="${t("howto.flipAria")}" aria-pressed="false">
            <span class="flip-icon flip-face-front" aria-hidden="true">❔</span>
            <span class="flip-icon flip-face-back" aria-hidden="true">←</span>
            <span class="flip-label flip-face-front">${t("howto.button")}</span>
            <span class="flip-label flip-face-back">${t("howto.back")}</span>
          </button>
          <div class="feature-inner">
            <div class="feature-front">
              <div class="feature-head">
                <span class="id">#${f.id}</span>
                <h3>${fTitle}</h3>
              </div>
              <p class="feature-desc">${fDesc}</p>
              <div class="levels">${levels}</div>
            </div>
            <div class="feature-back" aria-hidden="true">
              <div class="feature-head">
                <span class="id">#${f.id}</span>
                <h3>${fTitle}</h3>
              </div>
              <div class="howto-body">${howtoBody}</div>
            </div>
          </div>
          <div class="feature-actions">
            <button type="button" class="feature-note-toggle" data-note-toggle="${noteId}">
              <span class="note-icon">${hasNote ? "📝" : "+"}</span>
              <span class="note-label">${noteLabel}</span>
            </button>
            <span class="feature-ai-wrap">
              <button type="button" class="feature-ai-copy" data-ai-toggle title="${t("ai.askTitle")}">
                <span class="ai-icon">🤖</span>
                <span class="ai-label">${t("ai.ask")}</span>
              </button>
              <span class="feature-ai-options">
                <button type="button" class="feature-ai-option ai-tr" data-ai-format="tr" data-ai-cat="${cat.id}" data-ai-feat="${f.id}" title="${t("ai.trTitle")}">${t("ai.tr")}</button>
                <button type="button" class="feature-ai-option ai-json" data-ai-format="json" data-ai-cat="${cat.id}" data-ai-feat="${f.id}" title="${t("ai.jsonTitle")}">${t("ai.json")}</button>
              </span>
            </span>
          </div>
          <div class="feature-note">
            <textarea data-note-input="${noteId}" placeholder="${t("note.placeholder")}">${escapeHtml(noteValue)}</textarea>
            <div class="note-meta">
              <span>${t("note.autoSave")}</span>
              <button type="button" class="note-clear" data-note-clear="${noteId}">${t("note.clear")}</button>
            </div>
          </div>
          <div class="feature-note-display" aria-hidden="true">
            <span class="note-display-icon" aria-hidden="true">📝</span>
            <span class="note-display-text">${escapeHtml(noteValue)}</span>
          </div>
        </article>`;
    }).join("");

    /* If every feature in this category is framework-variant and no framework
       has been chosen, hide the entire category. */
    if (!features.trim()) return "";

    const collapsedClass = collapsedCats.has(`cat-${cat.id}`) ? " collapsed" : "";

    return `
      <section class="category${collapsedClass}" id="cat-${cat.id}">
        <header class="cat-header" data-cat-toggle="cat-${cat.id}">
          <span class="num">${cat.id}</span>
          <div class="title">
            <h2>${catTitle}</h2>
            <p>${catSub}</p>
          </div>
          <div class="cat-progress">
            <span class="pct" data-cat-pct="${cat.id}">0%</span>
            <span data-cat-num="${cat.id}">0 / 0</span>
          </div>
          <svg class="chevron" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><polyline points="6 9 12 15 18 9"></polyline></svg>
        </header>
        <div class="feature-list">${features}</div>
      </section>`;
  }).join("");
}

/* Update the "partial progress" visuals on the front-face .level row:
   the --step-progress CSS variable (used for the gradient fill) plus the
   .level-progress-badge percentage pill. Called after a step toggle, a level
   toggle, or setAllStepsChecked. With no steps, or with all or none checked,
   the partial fill is removed (a fully checked level already paints a solid
   background). */
function updateLevelProgressUI(levelKey) {
  const safe = (typeof CSS !== "undefined" && CSS.escape) ? CSS.escape(levelKey) : levelKey;
  const levelEl = document.querySelector(`.level[data-key="${safe}"]`);
  if (!levelEl) return;
  const steps = document.querySelectorAll(`.howto-step[data-step-key^="${safe}.s"]`);
  const total = steps.length;
  let badge = levelEl.querySelector(".level-progress-badge");

  if (total === 0) {
    /* No steps means no progress to show. */
    levelEl.style.removeProperty("--step-progress");
    if (badge) badge.remove();
    return;
  }

  const done = Array.from(steps).filter(li => state[li.dataset.stepKey]).length;
  const isPartial = done > 0 && done < total;

  if (isPartial) {
    const pct = Math.round((done / total) * 100);
    levelEl.style.setProperty("--step-progress", `${pct}%`);
    if (!badge) {
      badge = document.createElement("span");
      badge.className = "level-progress-badge";
      levelEl.appendChild(badge);
    }
    badge.textContent = `${pct}%`;
    badge.setAttribute("aria-label", `${done} / ${total}`);
  } else {
    /* 0% or 100% complete: hide the partial fill and badge. */
    levelEl.style.removeProperty("--step-progress");
    if (badge) badge.remove();
  }
}

/* Check or uncheck every How-To step under a given level key (e.g. "1.1.mvp")
   at once. Updates the visual state on both the front (.level) and back
   (.howto-step) faces of the card; the state object remains the single
   source of truth. */
function setAllStepsChecked(levelKey, checked) {
  /* CSS.escape so attribute selectors stay safe for keys with digits and
     dots (which are unusual but valid in our state keys). */
  const safe = (typeof CSS !== "undefined" && CSS.escape) ? CSS.escape(levelKey) : levelKey;
  const steps = document.querySelectorAll(`.howto-step[data-step-key^="${safe}.s"]`);
  steps.forEach(li => {
    const k = li.dataset.stepKey;
    if (!k) return;
    if (checked) {
      state[k] = true;
      li.classList.add("checked");
      li.setAttribute("aria-checked", "true");
    } else {
      delete state[k];
      li.classList.remove("checked");
      li.setAttribute("aria-checked", "false");
    }
  });
}

/* When a single step is toggled, sync the front face: if every step in this
   level is now checked, mark the .level row as checked as well; if any step
   is unchecked, clear the .level row. The sync only runs when steps exist
   (i.e. the render produced at least one <li>). */
function syncLevelFromSteps(levelKey) {
  const safe = (typeof CSS !== "undefined" && CSS.escape) ? CSS.escape(levelKey) : levelKey;
  const steps = document.querySelectorAll(`.howto-step[data-step-key^="${safe}.s"]`);
  if (steps.length === 0) return;
  const allChecked = Array.from(steps).every(li => state[li.dataset.stepKey]);
  const levelEl = document.querySelector(`.level[data-key="${safe}"]`);
  if (allChecked) {
    if (!state[levelKey]) {
      state[levelKey] = true;
      if (levelEl) levelEl.classList.add("checked");
    }
  } else {
    if (state[levelKey]) {
      delete state[levelKey];
      if (levelEl) levelEl.classList.remove("checked");
    }
  }
}

function attachClickHandlers() {
  /* Level toggle: a click on the MVP or Release row on the front face.
     Also syncs every step on the back face: when the user marks "MVP is
     done", the steps in the How-To guide are treated as done too. The
     reverse direction (checking all steps to auto-check the level) is
     handled by syncLevelFromSteps. */
  document.querySelectorAll(".level").forEach(el => {
    el.addEventListener("click", () => {
      if (lockState) return; /* Lock is active: ignore changes. */
      const key = el.dataset.key;
      const willCheck = !state[key];
      if (willCheck) { state[key] = true; el.classList.add("checked"); }
      else { delete state[key]; el.classList.remove("checked"); }
      /* Keep the back-face steps in sync with the level. */
      setAllStepsChecked(key, willCheck);
      /* Reset the partial fill / badge: the level is now fully checked or empty. */
      updateLevelProgressUI(key);
      saveState();
      updateProgress();
      if (viewFilter !== "all" || viewMode !== "both") applyFilters();
    });
  });

  /* How-To steps: each <li> is a clickable checkbox. Toggling persists to
     state and, when appropriate, syncs the parent level. Enter and Space
     also trigger the toggle for keyboard users. */
  document.querySelectorAll(".howto-step[data-step-key]").forEach(li => {
    const toggle = () => {
      if (lockState) return;
      const key = li.dataset.stepKey;
      if (!key) return;
      const willCheck = !state[key];
      if (willCheck) {
        state[key] = true;
        li.classList.add("checked");
        li.setAttribute("aria-checked", "true");
      } else {
        delete state[key];
        li.classList.remove("checked");
        li.setAttribute("aria-checked", "false");
      }
      /* The level key is the step key with its trailing ".sN" segment stripped. */
      const levelKey = key.replace(/\.s\d+$/, "");
      syncLevelFromSteps(levelKey);
      updateLevelProgressUI(levelKey);
      saveState();
      updateProgress();
      if (viewFilter !== "all" || viewMode !== "both") applyFilters();
    };
    li.addEventListener("click", toggle);
    li.addEventListener("keydown", (e) => {
      if (e.key === "Enter" || e.key === " ") {
        e.preventDefault();
        toggle();
      }
    });
  });

  /* Click on a category header toggles collapse / expand. */
  document.querySelectorAll(".cat-header").forEach(h => {
    h.addEventListener("click", () => {
      const catId = h.dataset.catToggle;
      if (!catId) return;
      const cat = document.getElementById(catId);
      if (!cat) return;
      const isCollapsed = cat.classList.toggle("collapsed");
      if (isCollapsed) collapsedCats.add(catId);
      else collapsedCats.delete(catId);
      saveCollapsed();
      /* Direct collapse-state interaction: the user deliberately opened or
         closed a category. */
      if (typeof markCollapseTouched === "function") markCollapseTouched();
      /* One category changed: do we still have an "all open" / "all closed"
         state or did we drop into a mixed state? Sync the toolbar pair. */
      if (typeof updateToolbarButtonStates === "function") updateToolbarButtonStates();
    });
  });

  /* Add a note / toggle the note panel open or closed. */
  document.querySelectorAll("[data-note-toggle]").forEach(btn => {
    btn.addEventListener("click", () => {
      const feature = btn.closest(".feature");
      feature.classList.toggle("note-open");
      if (feature.classList.contains("note-open")) {
        const ta = feature.querySelector("textarea");
        if (ta) setTimeout(() => ta.focus(), 50);
      }
    });
  });

  /* Save note content while the user is typing (with a debounced toast). */
  document.querySelectorAll("[data-note-input]").forEach(ta => {
    let toastTimer = null;
    ta.addEventListener("input", () => {
      const id = ta.dataset.noteInput;
      const value = ta.value;
      const feature = ta.closest(".feature");
      const toggle = feature.querySelector("[data-note-toggle]");
      if (value.trim()) {
        notes[id] = value;
        feature.classList.add("has-note");
        if (toggle) {
          toggle.querySelector(".note-icon").textContent = "📝";
          toggle.querySelector(".note-label").textContent = t("note.mine");
        }
      } else {
        delete notes[id];
        feature.classList.remove("has-note");
        if (toggle) {
          toggle.querySelector(".note-icon").textContent = "+";
          toggle.querySelector(".note-label").textContent = t("note.add");
        }
      }
      saveNotes();
      /* Also update the note card shown in presentation mode (if present). */
      const displayEl = feature.querySelector(".note-display-text");
      if (displayEl) displayEl.textContent = value;
      /* The Export button should be active even when only a note has been
         entered (no checked items), so refresh toolbar states. */
      if (typeof updateToolbarButtonStates === "function") updateToolbarButtonStates();
      clearTimeout(toastTimer);
      toastTimer = setTimeout(() => {
        showToast(value.trim() ? t("note.saved") : t("note.deleted"), "success", 1100);
      }, 700);
    });
  });

  /* Ask AI: toggle the format-selection panel open or closed. */
  document.querySelectorAll("[data-ai-toggle]").forEach(btn => {
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      const wrap = btn.closest(".feature-ai-wrap");
      const isOpen = wrap.classList.contains("ai-open");
      // Close any other open panels first so only one is visible at a time.
      document.querySelectorAll(".feature-ai-wrap.ai-open").forEach(w => {
        if (w !== wrap) w.classList.remove("ai-open");
      });
      wrap.classList.toggle("ai-open", !isOpen);
    });
  });

  /* AI format choice: copy a Turkish prompt or an English JSON prompt. */
  document.querySelectorAll("[data-ai-format]").forEach(btn => {
    btn.addEventListener("click", async (e) => {
      e.stopPropagation();
      const format = btn.dataset.aiFormat;
      const catId = btn.dataset.aiCat;
      const featId = btn.dataset.aiFeat;
      const cat = DATA.find(c => c.id === catId);
      const f = cat ? cat.features.find(x => x.id === featId) : null;
      if (!cat || !f) return;
      const prompt = format === "json" ? buildAIPromptJSON(cat, f) : buildAIPromptTR(cat, f);
      const ok = await copyToClipboard(prompt);
      const wrap = btn.closest(".feature-ai-wrap");
      if (ok) {
        const originalText = btn.textContent;
        btn.classList.add("copied");
        btn.textContent = t("ai.copied");
        showToast(
          format === "json" ? t("ai.copiedJson") : t("ai.copiedTr"),
          "success",
          2400
        );
        setTimeout(() => {
          btn.classList.remove("copied");
          btn.textContent = originalText;
          if (wrap) wrap.classList.remove("ai-open");
        }, 1400);
      } else {
        showToast(t("ai.copyFail"), "warn", 1800);
      }
    });
  });

  /* How-To flip button: 3D-flips one card. Per-card independent; flipping one
     card does not affect any other. Purely visual: nothing in state is
     mutated (no checkbox, progress, or note is written). The height
     animation and aria/aria-pressed sync live inside flipFeatureCard. */
  document.querySelectorAll("[data-flip-toggle]").forEach(btn => {
    btn.addEventListener("click", (e) => {
      e.stopPropagation();
      const feature = btn.closest(".feature");
      if (!feature) return;
      const willFlip = !feature.classList.contains("flipped");
      flipFeatureCard(feature, willFlip);
      /* Direct flip-state interaction: the user deliberately flipped a single
         card. Set the flip-touched flag so the toolbar leaves its dim
         first-launch state. */
      if (typeof markFlipTouched === "function") markFlipTouched();
      /* One card flipped: the count of .flipped cards in the DOM may now
         match the total, be zero, or be mixed. Recompute the .active
         highlight for the toolbar pair. */
      if (typeof updateToolbarButtonStates === "function") updateToolbarButtonStates();
    });
  });

  /* Clear-note button. */
  document.querySelectorAll("[data-note-clear]").forEach(btn => {
    btn.addEventListener("click", () => {
      const feature = btn.closest(".feature");
      const ta = feature.querySelector("textarea");
      if (ta) {
        ta.value = "";
        ta.dispatchEvent(new Event("input"));
      }
    });
  });

  /* After every render: if the user has chosen "review" mode, silently flip
     all cards to the back face. attachClickHandlers runs right after each
     render, so the preference is reapplied automatically on every re-render
     (language, style, framework, backend, filter change, etc.). */
  if (typeof applyInitialCardMode === "function") {
    applyInitialCardMode();
  }
}


